### ISSUE TITLE
Phobos mod will work or not?

### ISSUE THREAD

**Issue by Ronitvasava** [glKarin/com.n0n3m4.diii4a#92]
I installed phobos mod it didn't work , there is any way for installation

**Comment by ALord7** [comment]
Phobos mod will not work on idTech4A++ because it uses the game code and needs to be compiled and added manually. But the fact is that Phobos mod currently does not have source code and it cannot be compiled. Perhaps with the release of the 3rd episode of Phobos, this mod will receive the source code and then it can be transferred to idTech4A++ (but provided that it does not change the game code much, such as The Dark Mod)
